# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bssh_sdk_2
from bssh_sdk_2.models.v2_user_settings_response import V2UserSettingsResponse  # noqa: E501
from bssh_sdk_2.rest import ApiException


class TestV2UserSettingsResponse(unittest.TestCase):
    """V2UserSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2UserSettingsResponse(self):
        """Test V2UserSettingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bssh_sdk_2.models.v2_user_settings_response.V2UserSettingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
