# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.library_container_compact import LibraryContainerCompact  # noqa: E501
from swagger_client.rest import ApiException


class TestLibraryContainerCompact(unittest.TestCase):
    """LibraryContainerCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryContainerCompact(self):
        """Test LibraryContainerCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.library_container_compact.LibraryContainerCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
