# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v2_ica_file_create_download_url_request import V2IcaFileCreateDownloadUrlRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV2IcaFileCreateDownloadUrlRequest(unittest.TestCase):
    """V2IcaFileCreateDownloadUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2IcaFileCreateDownloadUrlRequest(self):
        """Test V2IcaFileCreateDownloadUrlRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v2_ica_file_create_download_url_request.V2IcaFileCreateDownloadUrlRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
