# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1pre3_run_compact import V1pre3RunCompact  # noqa: E501
from swagger_client.rest import ApiException


class TestV1pre3RunCompact(unittest.TestCase):
    """V1pre3RunCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1pre3RunCompact(self):
        """Test V1pre3RunCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1pre3_run_compact.V1pre3RunCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
