# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v2_o_auth_v2_token_from_application_jwt_request import V2OAuthV2TokenFromApplicationJwtRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV2OAuthV2TokenFromApplicationJwtRequest(unittest.TestCase):
    """V2OAuthV2TokenFromApplicationJwtRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2OAuthV2TokenFromApplicationJwtRequest(self):
        """Test V2OAuthV2TokenFromApplicationJwtRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v2_o_auth_v2_token_from_application_jwt_request.V2OAuthV2TokenFromApplicationJwtRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
