# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bssh_sdk_2
from bssh_sdk_2.models.compute_statistics import ComputeStatistics  # noqa: E501
from bssh_sdk_2.rest import ApiException


class TestComputeStatistics(unittest.TestCase):
    """ComputeStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputeStatistics(self):
        """Test ComputeStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bssh_sdk_2.models.compute_statistics.ComputeStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
