# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.application_metadata_v2_api_response import ApplicationMetadataV2ApiResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationMetadataV2ApiResponse(unittest.TestCase):
    """ApplicationMetadataV2ApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationMetadataV2ApiResponse(self):
        """Test ApplicationMetadataV2ApiResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.application_metadata_v2_api_response.ApplicationMetadataV2ApiResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
