# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bssh_sdk_2
from bssh_sdk_2.models.v2_resource_presigned_url_complete_request_for_everyone import V2ResourcePresignedUrlCompleteRequestForEveryone  # noqa: E501
from bssh_sdk_2.rest import ApiException


class TestV2ResourcePresignedUrlCompleteRequestForEveryone(unittest.TestCase):
    """V2ResourcePresignedUrlCompleteRequestForEveryone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2ResourcePresignedUrlCompleteRequestForEveryone(self):
        """Test V2ResourcePresignedUrlCompleteRequestForEveryone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bssh_sdk_2.models.v2_resource_presigned_url_complete_request_for_everyone.V2ResourcePresignedUrlCompleteRequestForEveryone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
