# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1pre3_post_resource_id_files_request import V1pre3PostResourceIdFilesRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestV1pre3PostResourceIdFilesRequest(unittest.TestCase):
    """V1pre3PostResourceIdFilesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1pre3PostResourceIdFilesRequest(self):
        """Test V1pre3PostResourceIdFilesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1pre3_post_resource_id_files_request.V1pre3PostResourceIdFilesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
