# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metadatuple import Metadatuple  # noqa: E501
from swagger_client.rest import ApiException


class TestMetadatuple(unittest.TestCase):
    """Metadatuple unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadatuple(self):
        """Test Metadatuple"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metadatuple.Metadatuple()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
