# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1pre3LibraryPoolCompact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'href': 'str',
        'user_pool_id': 'str',
        'user_owned_by': 'V1pre3UserCompact',
        'library_count': 'int',
        'date_modified': 'datetime',
        'date_created': 'datetime',
        'status': 'str',
        'library_prep': 'StringICollection'
    }

    attribute_map = {
        'id': 'Id',
        'href': 'Href',
        'user_pool_id': 'UserPoolId',
        'user_owned_by': 'UserOwnedBy',
        'library_count': 'LibraryCount',
        'date_modified': 'DateModified',
        'date_created': 'DateCreated',
        'status': 'Status',
        'library_prep': 'LibraryPrep'
    }

    def __init__(self, id=None, href=None, user_pool_id=None, user_owned_by=None, library_count=None, date_modified=None, date_created=None, status=None, library_prep=None):  # noqa: E501
        """V1pre3LibraryPoolCompact - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._href = None
        self._user_pool_id = None
        self._user_owned_by = None
        self._library_count = None
        self._date_modified = None
        self._date_created = None
        self._status = None
        self._library_prep = None
        self.discriminator = None
        self.id = id
        if href is not None:
            self.href = href
        if user_pool_id is not None:
            self.user_pool_id = user_pool_id
        if user_owned_by is not None:
            self.user_owned_by = user_owned_by
        if library_count is not None:
            self.library_count = library_count
        if date_modified is not None:
            self.date_modified = date_modified
        if date_created is not None:
            self.date_created = date_created
        if status is not None:
            self.status = status
        if library_prep is not None:
            self.library_prep = library_prep

    @property
    def id(self):
        """Gets the id of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The id of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1pre3LibraryPoolCompact.


        :param id: The id of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def href(self):
        """Gets the href of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The href of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V1pre3LibraryPoolCompact.


        :param href: The href of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def user_pool_id(self):
        """Gets the user_pool_id of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The user_pool_id of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: str
        """
        return self._user_pool_id

    @user_pool_id.setter
    def user_pool_id(self, user_pool_id):
        """Sets the user_pool_id of this V1pre3LibraryPoolCompact.


        :param user_pool_id: The user_pool_id of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: str
        """

        self._user_pool_id = user_pool_id

    @property
    def user_owned_by(self):
        """Gets the user_owned_by of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The user_owned_by of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: V1pre3UserCompact
        """
        return self._user_owned_by

    @user_owned_by.setter
    def user_owned_by(self, user_owned_by):
        """Sets the user_owned_by of this V1pre3LibraryPoolCompact.


        :param user_owned_by: The user_owned_by of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: V1pre3UserCompact
        """

        self._user_owned_by = user_owned_by

    @property
    def library_count(self):
        """Gets the library_count of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The library_count of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: int
        """
        return self._library_count

    @library_count.setter
    def library_count(self, library_count):
        """Sets the library_count of this V1pre3LibraryPoolCompact.


        :param library_count: The library_count of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: int
        """

        self._library_count = library_count

    @property
    def date_modified(self):
        """Gets the date_modified of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The date_modified of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this V1pre3LibraryPoolCompact.


        :param date_modified: The date_modified of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def date_created(self):
        """Gets the date_created of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The date_created of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this V1pre3LibraryPoolCompact.


        :param date_created: The date_created of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def status(self):
        """Gets the status of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The status of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1pre3LibraryPoolCompact.


        :param status: The status of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def library_prep(self):
        """Gets the library_prep of this V1pre3LibraryPoolCompact.  # noqa: E501


        :return: The library_prep of this V1pre3LibraryPoolCompact.  # noqa: E501
        :rtype: StringICollection
        """
        return self._library_prep

    @library_prep.setter
    def library_prep(self, library_prep):
        """Sets the library_prep of this V1pre3LibraryPoolCompact.


        :param library_prep: The library_prep of this V1pre3LibraryPoolCompact.  # noqa: E501
        :type: StringICollection
        """

        self._library_prep = library_prep

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1pre3LibraryPoolCompact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1pre3LibraryPoolCompact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
