# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2AnalysisWorkflowDependency(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'attributes': 'dict(str, object)',
        'dependencies': 'list[V2AnalysisWorkflowDependency]'
    }

    attribute_map = {
        'type': 'Type',
        'attributes': 'Attributes',
        'dependencies': 'Dependencies'
    }

    def __init__(self, type=None, attributes=None, dependencies=None):  # noqa: E501
        """V2AnalysisWorkflowDependency - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._attributes = None
        self._dependencies = None
        self.discriminator = None
        self.type = type
        self.attributes = attributes
        self.dependencies = dependencies

    @property
    def type(self):
        """Gets the type of this V2AnalysisWorkflowDependency.  # noqa: E501

        The type of dependency to add, valid operators include: “BioSampleYield”, “AppCompletion”  # noqa: E501

        :return: The type of this V2AnalysisWorkflowDependency.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2AnalysisWorkflowDependency.

        The type of dependency to add, valid operators include: “BioSampleYield”, “AppCompletion”  # noqa: E501

        :param type: The type of this V2AnalysisWorkflowDependency.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def attributes(self):
        """Gets the attributes of this V2AnalysisWorkflowDependency.  # noqa: E501

        Sections containing a list of attributes and their values defining the app launch dependency, specific to the dependency type given  # noqa: E501

        :return: The attributes of this V2AnalysisWorkflowDependency.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this V2AnalysisWorkflowDependency.

        Sections containing a list of attributes and their values defining the app launch dependency, specific to the dependency type given  # noqa: E501

        :param attributes: The attributes of this V2AnalysisWorkflowDependency.  # noqa: E501
        :type: dict(str, object)
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    @property
    def dependencies(self):
        """Gets the dependencies of this V2AnalysisWorkflowDependency.  # noqa: E501

        Optional nested dependencies, not needed for BioSampleYield or AppCompletion dependency types  # noqa: E501

        :return: The dependencies of this V2AnalysisWorkflowDependency.  # noqa: E501
        :rtype: list[V2AnalysisWorkflowDependency]
        """
        return self._dependencies

    @dependencies.setter
    def dependencies(self, dependencies):
        """Sets the dependencies of this V2AnalysisWorkflowDependency.

        Optional nested dependencies, not needed for BioSampleYield or AppCompletion dependency types  # noqa: E501

        :param dependencies: The dependencies of this V2AnalysisWorkflowDependency.  # noqa: E501
        :type: list[V2AnalysisWorkflowDependency]
        """
        if dependencies is None:
            raise ValueError("Invalid value for `dependencies`, must not be `None`")  # noqa: E501

        self._dependencies = dependencies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2AnalysisWorkflowDependency, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2AnalysisWorkflowDependency):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
