# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'str',
        'error_message': 'str',
        'request_id': 'str',
        'additional_data': 'IDictionary'
    }

    attribute_map = {
        'error_code': 'ErrorCode',
        'error_message': 'ErrorMessage',
        'request_id': 'RequestId',
        'additional_data': 'AdditionalData'
    }

    def __init__(self, error_code=None, error_message=None, request_id=None, additional_data=None):  # noqa: E501
        """V2Error - a model defined in Swagger"""  # noqa: E501
        self._error_code = None
        self._error_message = None
        self._request_id = None
        self._additional_data = None
        self.discriminator = None
        self.error_code = error_code
        self.error_message = error_message
        self.request_id = request_id
        self.additional_data = additional_data

    @property
    def error_code(self):
        """Gets the error_code of this V2Error.  # noqa: E501


        :return: The error_code of this V2Error.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this V2Error.


        :param error_code: The error_code of this V2Error.  # noqa: E501
        :type: str
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def error_message(self):
        """Gets the error_message of this V2Error.  # noqa: E501


        :return: The error_message of this V2Error.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this V2Error.


        :param error_message: The error_message of this V2Error.  # noqa: E501
        :type: str
        """
        if error_message is None:
            raise ValueError("Invalid value for `error_message`, must not be `None`")  # noqa: E501

        self._error_message = error_message

    @property
    def request_id(self):
        """Gets the request_id of this V2Error.  # noqa: E501


        :return: The request_id of this V2Error.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this V2Error.


        :param request_id: The request_id of this V2Error.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def additional_data(self):
        """Gets the additional_data of this V2Error.  # noqa: E501


        :return: The additional_data of this V2Error.  # noqa: E501
        :rtype: IDictionary
        """
        return self._additional_data

    @additional_data.setter
    def additional_data(self, additional_data):
        """Sets the additional_data of this V2Error.


        :param additional_data: The additional_data of this V2Error.  # noqa: E501
        :type: IDictionary
        """
        if additional_data is None:
            raise ValueError("Invalid value for `additional_data`, must not be `None`")  # noqa: E501

        self._additional_data = additional_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2Error, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
