# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2PostApplicationIdWorkflowsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'short_description': 'str',
        'app_session_id': 'str'
    }

    attribute_map = {
        'name': 'Name',
        'short_description': 'ShortDescription',
        'app_session_id': 'AppSessionId'
    }

    def __init__(self, name=None, short_description=None, app_session_id=None):  # noqa: E501
        """V2PostApplicationIdWorkflowsRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._short_description = None
        self._app_session_id = None
        self.discriminator = None
        self.name = name
        self.short_description = short_description
        self.app_session_id = app_session_id

    @property
    def name(self):
        """Gets the name of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501

        The name of the analysis workflow  # noqa: E501

        :return: The name of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2PostApplicationIdWorkflowsRequest.

        The name of the analysis workflow  # noqa: E501

        :param name: The name of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def short_description(self):
        """Gets the short_description of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501

        Description of the analysis workflow  # noqa: E501

        :return: The short_description of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """Sets the short_description of this V2PostApplicationIdWorkflowsRequest.

        Description of the analysis workflow  # noqa: E501

        :param short_description: The short_description of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :type: str
        """
        if short_description is None:
            raise ValueError("Invalid value for `short_description`, must not be `None`")  # noqa: E501

        self._short_description = short_description

    @property
    def app_session_id(self):
        """Gets the app_session_id of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501

        The ID of the appsession to gather settings from when creating the workflow  # noqa: E501

        :return: The app_session_id of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :rtype: str
        """
        return self._app_session_id

    @app_session_id.setter
    def app_session_id(self, app_session_id):
        """Sets the app_session_id of this V2PostApplicationIdWorkflowsRequest.

        The ID of the appsession to gather settings from when creating the workflow  # noqa: E501

        :param app_session_id: The app_session_id of this V2PostApplicationIdWorkflowsRequest.  # noqa: E501
        :type: str
        """
        if app_session_id is None:
            raise ValueError("Invalid value for `app_session_id`, must not be `None`")  # noqa: E501

        self._app_session_id = app_session_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2PostApplicationIdWorkflowsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2PostApplicationIdWorkflowsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
