# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2PostLibraryPoolIdRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_pool_id': 'str',
        'notes': 'str',
        'status': 'str'
    }

    attribute_map = {
        'user_pool_id': 'UserPoolId',
        'notes': 'Notes',
        'status': 'Status'
    }

    def __init__(self, user_pool_id=None, notes=None, status=None):  # noqa: E501
        """V2PostLibraryPoolIdRequest - a model defined in Swagger"""  # noqa: E501
        self._user_pool_id = None
        self._notes = None
        self._status = None
        self.discriminator = None
        self.user_pool_id = user_pool_id
        self.notes = notes
        self.status = status

    @property
    def user_pool_id(self):
        """Gets the user_pool_id of this V2PostLibraryPoolIdRequest.  # noqa: E501


        :return: The user_pool_id of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_pool_id

    @user_pool_id.setter
    def user_pool_id(self, user_pool_id):
        """Sets the user_pool_id of this V2PostLibraryPoolIdRequest.


        :param user_pool_id: The user_pool_id of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :type: str
        """
        if user_pool_id is None:
            raise ValueError("Invalid value for `user_pool_id`, must not be `None`")  # noqa: E501

        self._user_pool_id = user_pool_id

    @property
    def notes(self):
        """Gets the notes of this V2PostLibraryPoolIdRequest.  # noqa: E501


        :return: The notes of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this V2PostLibraryPoolIdRequest.


        :param notes: The notes of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :type: str
        """
        if notes is None:
            raise ValueError("Invalid value for `notes`, must not be `None`")  # noqa: E501

        self._notes = notes

    @property
    def status(self):
        """Gets the status of this V2PostLibraryPoolIdRequest.  # noqa: E501

        Possible values are: Active, Failed, Consumed, QCFailed  # noqa: E501

        :return: The status of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V2PostLibraryPoolIdRequest.

        Possible values are: Active, Failed, Consumed, QCFailed  # noqa: E501

        :param status: The status of this V2PostLibraryPoolIdRequest.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2PostLibraryPoolIdRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2PostLibraryPoolIdRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
