# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2Property(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_modified_by': 'V1pre3UserCompact',
        'application_modified_by': 'V1pre3ApplicationCompact',
        'date_modified': 'datetime',
        'type': 'str',
        'href': 'str',
        'name': 'str',
        'description': 'str',
        'content': 'str',
        'content_map': 'MapContent',
        'application': 'V1pre3ApplicationCompact',
        'app_session': 'V2AppSessionCompact',
        'bio_sample': 'V2BiologicalSampleCompact',
        'dataset': 'V2DatasetCompact',
        'file': 'V1pre3FileCompact',
        'sample_library': 'V2LibraryCompact',
        'library_pool': 'V1pre3LibraryPoolCompact',
        'project': 'V1pre3ProjectCompact',
        'run': 'V1pre3RunCompact',
        'subject': 'V2SubjectCompact',
        'user': 'V1pre3UserCompact',
        'content_map_items': 'list[MapContent]',
        'content_items': 'list[str]',
        'application_items': 'list[V1pre3ApplicationCompact]',
        'app_session_items': 'list[V2AppSessionCompact]',
        'bio_sample_items': 'list[V2BiologicalSampleCompact]',
        'dataset_items': 'list[V2DatasetCompact]',
        'file_items': 'list[V1pre3FileCompact]',
        'sample_library_items': 'list[V2LibraryCompact]',
        'library_pool_items': 'list[V1pre3LibraryPoolCompact]',
        'project_items': 'list[V1pre3ProjectCompact]',
        'run_items': 'list[V1pre3RunCompact]',
        'subject_items': 'list[V2SubjectCompact]',
        'user_items': 'list[V1pre3UserCompact]',
        'href_items': 'str',
        'items_displayed_count': 'int',
        'items_total_count': 'int',
        'allow_duplicates': 'bool'
    }

    attribute_map = {
        'user_modified_by': 'UserModifiedBy',
        'application_modified_by': 'ApplicationModifiedBy',
        'date_modified': 'DateModified',
        'type': 'Type',
        'href': 'Href',
        'name': 'Name',
        'description': 'Description',
        'content': 'Content',
        'content_map': 'ContentMap',
        'application': 'Application',
        'app_session': 'AppSession',
        'bio_sample': 'BioSample',
        'dataset': 'Dataset',
        'file': 'File',
        'sample_library': 'SampleLibrary',
        'library_pool': 'LibraryPool',
        'project': 'Project',
        'run': 'Run',
        'subject': 'Subject',
        'user': 'User',
        'content_map_items': 'ContentMapItems',
        'content_items': 'ContentItems',
        'application_items': 'ApplicationItems',
        'app_session_items': 'AppSessionItems',
        'bio_sample_items': 'BioSampleItems',
        'dataset_items': 'DatasetItems',
        'file_items': 'FileItems',
        'sample_library_items': 'SampleLibraryItems',
        'library_pool_items': 'LibraryPoolItems',
        'project_items': 'ProjectItems',
        'run_items': 'RunItems',
        'subject_items': 'SubjectItems',
        'user_items': 'UserItems',
        'href_items': 'HrefItems',
        'items_displayed_count': 'ItemsDisplayedCount',
        'items_total_count': 'ItemsTotalCount',
        'allow_duplicates': 'AllowDuplicates'
    }

    def __init__(self, user_modified_by=None, application_modified_by=None, date_modified=None, type=None, href=None, name=None, description=None, content=None, content_map=None, application=None, app_session=None, bio_sample=None, dataset=None, file=None, sample_library=None, library_pool=None, project=None, run=None, subject=None, user=None, content_map_items=None, content_items=None, application_items=None, app_session_items=None, bio_sample_items=None, dataset_items=None, file_items=None, sample_library_items=None, library_pool_items=None, project_items=None, run_items=None, subject_items=None, user_items=None, href_items=None, items_displayed_count=None, items_total_count=None, allow_duplicates=None):  # noqa: E501
        """V2Property - a model defined in Swagger"""  # noqa: E501
        self._user_modified_by = None
        self._application_modified_by = None
        self._date_modified = None
        self._type = None
        self._href = None
        self._name = None
        self._description = None
        self._content = None
        self._content_map = None
        self._application = None
        self._app_session = None
        self._bio_sample = None
        self._dataset = None
        self._file = None
        self._sample_library = None
        self._library_pool = None
        self._project = None
        self._run = None
        self._subject = None
        self._user = None
        self._content_map_items = None
        self._content_items = None
        self._application_items = None
        self._app_session_items = None
        self._bio_sample_items = None
        self._dataset_items = None
        self._file_items = None
        self._sample_library_items = None
        self._library_pool_items = None
        self._project_items = None
        self._run_items = None
        self._subject_items = None
        self._user_items = None
        self._href_items = None
        self._items_displayed_count = None
        self._items_total_count = None
        self._allow_duplicates = None
        self.discriminator = None
        if user_modified_by is not None:
            self.user_modified_by = user_modified_by
        if application_modified_by is not None:
            self.application_modified_by = application_modified_by
        if date_modified is not None:
            self.date_modified = date_modified
        if type is not None:
            self.type = type
        if href is not None:
            self.href = href
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if content is not None:
            self.content = content
        if content_map is not None:
            self.content_map = content_map
        if application is not None:
            self.application = application
        if app_session is not None:
            self.app_session = app_session
        if bio_sample is not None:
            self.bio_sample = bio_sample
        if dataset is not None:
            self.dataset = dataset
        if file is not None:
            self.file = file
        if sample_library is not None:
            self.sample_library = sample_library
        if library_pool is not None:
            self.library_pool = library_pool
        if project is not None:
            self.project = project
        if run is not None:
            self.run = run
        if subject is not None:
            self.subject = subject
        if user is not None:
            self.user = user
        if content_map_items is not None:
            self.content_map_items = content_map_items
        if content_items is not None:
            self.content_items = content_items
        if application_items is not None:
            self.application_items = application_items
        if app_session_items is not None:
            self.app_session_items = app_session_items
        if bio_sample_items is not None:
            self.bio_sample_items = bio_sample_items
        if dataset_items is not None:
            self.dataset_items = dataset_items
        if file_items is not None:
            self.file_items = file_items
        if sample_library_items is not None:
            self.sample_library_items = sample_library_items
        if library_pool_items is not None:
            self.library_pool_items = library_pool_items
        if project_items is not None:
            self.project_items = project_items
        if run_items is not None:
            self.run_items = run_items
        if subject_items is not None:
            self.subject_items = subject_items
        if user_items is not None:
            self.user_items = user_items
        if href_items is not None:
            self.href_items = href_items
        if items_displayed_count is not None:
            self.items_displayed_count = items_displayed_count
        if items_total_count is not None:
            self.items_total_count = items_total_count
        if allow_duplicates is not None:
            self.allow_duplicates = allow_duplicates

    @property
    def user_modified_by(self):
        """Gets the user_modified_by of this V2Property.  # noqa: E501


        :return: The user_modified_by of this V2Property.  # noqa: E501
        :rtype: V1pre3UserCompact
        """
        return self._user_modified_by

    @user_modified_by.setter
    def user_modified_by(self, user_modified_by):
        """Sets the user_modified_by of this V2Property.


        :param user_modified_by: The user_modified_by of this V2Property.  # noqa: E501
        :type: V1pre3UserCompact
        """

        self._user_modified_by = user_modified_by

    @property
    def application_modified_by(self):
        """Gets the application_modified_by of this V2Property.  # noqa: E501


        :return: The application_modified_by of this V2Property.  # noqa: E501
        :rtype: V1pre3ApplicationCompact
        """
        return self._application_modified_by

    @application_modified_by.setter
    def application_modified_by(self, application_modified_by):
        """Sets the application_modified_by of this V2Property.


        :param application_modified_by: The application_modified_by of this V2Property.  # noqa: E501
        :type: V1pre3ApplicationCompact
        """

        self._application_modified_by = application_modified_by

    @property
    def date_modified(self):
        """Gets the date_modified of this V2Property.  # noqa: E501


        :return: The date_modified of this V2Property.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this V2Property.


        :param date_modified: The date_modified of this V2Property.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def type(self):
        """Gets the type of this V2Property.  # noqa: E501


        :return: The type of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V2Property.


        :param type: The type of this V2Property.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def href(self):
        """Gets the href of this V2Property.  # noqa: E501


        :return: The href of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2Property.


        :param href: The href of this V2Property.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def name(self):
        """Gets the name of this V2Property.  # noqa: E501


        :return: The name of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2Property.


        :param name: The name of this V2Property.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this V2Property.  # noqa: E501


        :return: The description of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V2Property.


        :param description: The description of this V2Property.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def content(self):
        """Gets the content of this V2Property.  # noqa: E501


        :return: The content of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this V2Property.


        :param content: The content of this V2Property.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def content_map(self):
        """Gets the content_map of this V2Property.  # noqa: E501


        :return: The content_map of this V2Property.  # noqa: E501
        :rtype: MapContent
        """
        return self._content_map

    @content_map.setter
    def content_map(self, content_map):
        """Sets the content_map of this V2Property.


        :param content_map: The content_map of this V2Property.  # noqa: E501
        :type: MapContent
        """

        self._content_map = content_map

    @property
    def application(self):
        """Gets the application of this V2Property.  # noqa: E501


        :return: The application of this V2Property.  # noqa: E501
        :rtype: V1pre3ApplicationCompact
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this V2Property.


        :param application: The application of this V2Property.  # noqa: E501
        :type: V1pre3ApplicationCompact
        """

        self._application = application

    @property
    def app_session(self):
        """Gets the app_session of this V2Property.  # noqa: E501


        :return: The app_session of this V2Property.  # noqa: E501
        :rtype: V2AppSessionCompact
        """
        return self._app_session

    @app_session.setter
    def app_session(self, app_session):
        """Sets the app_session of this V2Property.


        :param app_session: The app_session of this V2Property.  # noqa: E501
        :type: V2AppSessionCompact
        """

        self._app_session = app_session

    @property
    def bio_sample(self):
        """Gets the bio_sample of this V2Property.  # noqa: E501


        :return: The bio_sample of this V2Property.  # noqa: E501
        :rtype: V2BiologicalSampleCompact
        """
        return self._bio_sample

    @bio_sample.setter
    def bio_sample(self, bio_sample):
        """Sets the bio_sample of this V2Property.


        :param bio_sample: The bio_sample of this V2Property.  # noqa: E501
        :type: V2BiologicalSampleCompact
        """

        self._bio_sample = bio_sample

    @property
    def dataset(self):
        """Gets the dataset of this V2Property.  # noqa: E501


        :return: The dataset of this V2Property.  # noqa: E501
        :rtype: V2DatasetCompact
        """
        return self._dataset

    @dataset.setter
    def dataset(self, dataset):
        """Sets the dataset of this V2Property.


        :param dataset: The dataset of this V2Property.  # noqa: E501
        :type: V2DatasetCompact
        """

        self._dataset = dataset

    @property
    def file(self):
        """Gets the file of this V2Property.  # noqa: E501


        :return: The file of this V2Property.  # noqa: E501
        :rtype: V1pre3FileCompact
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this V2Property.


        :param file: The file of this V2Property.  # noqa: E501
        :type: V1pre3FileCompact
        """

        self._file = file

    @property
    def sample_library(self):
        """Gets the sample_library of this V2Property.  # noqa: E501


        :return: The sample_library of this V2Property.  # noqa: E501
        :rtype: V2LibraryCompact
        """
        return self._sample_library

    @sample_library.setter
    def sample_library(self, sample_library):
        """Sets the sample_library of this V2Property.


        :param sample_library: The sample_library of this V2Property.  # noqa: E501
        :type: V2LibraryCompact
        """

        self._sample_library = sample_library

    @property
    def library_pool(self):
        """Gets the library_pool of this V2Property.  # noqa: E501


        :return: The library_pool of this V2Property.  # noqa: E501
        :rtype: V1pre3LibraryPoolCompact
        """
        return self._library_pool

    @library_pool.setter
    def library_pool(self, library_pool):
        """Sets the library_pool of this V2Property.


        :param library_pool: The library_pool of this V2Property.  # noqa: E501
        :type: V1pre3LibraryPoolCompact
        """

        self._library_pool = library_pool

    @property
    def project(self):
        """Gets the project of this V2Property.  # noqa: E501


        :return: The project of this V2Property.  # noqa: E501
        :rtype: V1pre3ProjectCompact
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this V2Property.


        :param project: The project of this V2Property.  # noqa: E501
        :type: V1pre3ProjectCompact
        """

        self._project = project

    @property
    def run(self):
        """Gets the run of this V2Property.  # noqa: E501


        :return: The run of this V2Property.  # noqa: E501
        :rtype: V1pre3RunCompact
        """
        return self._run

    @run.setter
    def run(self, run):
        """Sets the run of this V2Property.


        :param run: The run of this V2Property.  # noqa: E501
        :type: V1pre3RunCompact
        """

        self._run = run

    @property
    def subject(self):
        """Gets the subject of this V2Property.  # noqa: E501


        :return: The subject of this V2Property.  # noqa: E501
        :rtype: V2SubjectCompact
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this V2Property.


        :param subject: The subject of this V2Property.  # noqa: E501
        :type: V2SubjectCompact
        """

        self._subject = subject

    @property
    def user(self):
        """Gets the user of this V2Property.  # noqa: E501


        :return: The user of this V2Property.  # noqa: E501
        :rtype: V1pre3UserCompact
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this V2Property.


        :param user: The user of this V2Property.  # noqa: E501
        :type: V1pre3UserCompact
        """

        self._user = user

    @property
    def content_map_items(self):
        """Gets the content_map_items of this V2Property.  # noqa: E501


        :return: The content_map_items of this V2Property.  # noqa: E501
        :rtype: list[MapContent]
        """
        return self._content_map_items

    @content_map_items.setter
    def content_map_items(self, content_map_items):
        """Sets the content_map_items of this V2Property.


        :param content_map_items: The content_map_items of this V2Property.  # noqa: E501
        :type: list[MapContent]
        """

        self._content_map_items = content_map_items

    @property
    def content_items(self):
        """Gets the content_items of this V2Property.  # noqa: E501


        :return: The content_items of this V2Property.  # noqa: E501
        :rtype: list[str]
        """
        return self._content_items

    @content_items.setter
    def content_items(self, content_items):
        """Sets the content_items of this V2Property.


        :param content_items: The content_items of this V2Property.  # noqa: E501
        :type: list[str]
        """

        self._content_items = content_items

    @property
    def application_items(self):
        """Gets the application_items of this V2Property.  # noqa: E501


        :return: The application_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3ApplicationCompact]
        """
        return self._application_items

    @application_items.setter
    def application_items(self, application_items):
        """Sets the application_items of this V2Property.


        :param application_items: The application_items of this V2Property.  # noqa: E501
        :type: list[V1pre3ApplicationCompact]
        """

        self._application_items = application_items

    @property
    def app_session_items(self):
        """Gets the app_session_items of this V2Property.  # noqa: E501


        :return: The app_session_items of this V2Property.  # noqa: E501
        :rtype: list[V2AppSessionCompact]
        """
        return self._app_session_items

    @app_session_items.setter
    def app_session_items(self, app_session_items):
        """Sets the app_session_items of this V2Property.


        :param app_session_items: The app_session_items of this V2Property.  # noqa: E501
        :type: list[V2AppSessionCompact]
        """

        self._app_session_items = app_session_items

    @property
    def bio_sample_items(self):
        """Gets the bio_sample_items of this V2Property.  # noqa: E501


        :return: The bio_sample_items of this V2Property.  # noqa: E501
        :rtype: list[V2BiologicalSampleCompact]
        """
        return self._bio_sample_items

    @bio_sample_items.setter
    def bio_sample_items(self, bio_sample_items):
        """Sets the bio_sample_items of this V2Property.


        :param bio_sample_items: The bio_sample_items of this V2Property.  # noqa: E501
        :type: list[V2BiologicalSampleCompact]
        """

        self._bio_sample_items = bio_sample_items

    @property
    def dataset_items(self):
        """Gets the dataset_items of this V2Property.  # noqa: E501


        :return: The dataset_items of this V2Property.  # noqa: E501
        :rtype: list[V2DatasetCompact]
        """
        return self._dataset_items

    @dataset_items.setter
    def dataset_items(self, dataset_items):
        """Sets the dataset_items of this V2Property.


        :param dataset_items: The dataset_items of this V2Property.  # noqa: E501
        :type: list[V2DatasetCompact]
        """

        self._dataset_items = dataset_items

    @property
    def file_items(self):
        """Gets the file_items of this V2Property.  # noqa: E501


        :return: The file_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3FileCompact]
        """
        return self._file_items

    @file_items.setter
    def file_items(self, file_items):
        """Sets the file_items of this V2Property.


        :param file_items: The file_items of this V2Property.  # noqa: E501
        :type: list[V1pre3FileCompact]
        """

        self._file_items = file_items

    @property
    def sample_library_items(self):
        """Gets the sample_library_items of this V2Property.  # noqa: E501


        :return: The sample_library_items of this V2Property.  # noqa: E501
        :rtype: list[V2LibraryCompact]
        """
        return self._sample_library_items

    @sample_library_items.setter
    def sample_library_items(self, sample_library_items):
        """Sets the sample_library_items of this V2Property.


        :param sample_library_items: The sample_library_items of this V2Property.  # noqa: E501
        :type: list[V2LibraryCompact]
        """

        self._sample_library_items = sample_library_items

    @property
    def library_pool_items(self):
        """Gets the library_pool_items of this V2Property.  # noqa: E501


        :return: The library_pool_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3LibraryPoolCompact]
        """
        return self._library_pool_items

    @library_pool_items.setter
    def library_pool_items(self, library_pool_items):
        """Sets the library_pool_items of this V2Property.


        :param library_pool_items: The library_pool_items of this V2Property.  # noqa: E501
        :type: list[V1pre3LibraryPoolCompact]
        """

        self._library_pool_items = library_pool_items

    @property
    def project_items(self):
        """Gets the project_items of this V2Property.  # noqa: E501


        :return: The project_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3ProjectCompact]
        """
        return self._project_items

    @project_items.setter
    def project_items(self, project_items):
        """Sets the project_items of this V2Property.


        :param project_items: The project_items of this V2Property.  # noqa: E501
        :type: list[V1pre3ProjectCompact]
        """

        self._project_items = project_items

    @property
    def run_items(self):
        """Gets the run_items of this V2Property.  # noqa: E501


        :return: The run_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3RunCompact]
        """
        return self._run_items

    @run_items.setter
    def run_items(self, run_items):
        """Sets the run_items of this V2Property.


        :param run_items: The run_items of this V2Property.  # noqa: E501
        :type: list[V1pre3RunCompact]
        """

        self._run_items = run_items

    @property
    def subject_items(self):
        """Gets the subject_items of this V2Property.  # noqa: E501


        :return: The subject_items of this V2Property.  # noqa: E501
        :rtype: list[V2SubjectCompact]
        """
        return self._subject_items

    @subject_items.setter
    def subject_items(self, subject_items):
        """Sets the subject_items of this V2Property.


        :param subject_items: The subject_items of this V2Property.  # noqa: E501
        :type: list[V2SubjectCompact]
        """

        self._subject_items = subject_items

    @property
    def user_items(self):
        """Gets the user_items of this V2Property.  # noqa: E501


        :return: The user_items of this V2Property.  # noqa: E501
        :rtype: list[V1pre3UserCompact]
        """
        return self._user_items

    @user_items.setter
    def user_items(self, user_items):
        """Sets the user_items of this V2Property.


        :param user_items: The user_items of this V2Property.  # noqa: E501
        :type: list[V1pre3UserCompact]
        """

        self._user_items = user_items

    @property
    def href_items(self):
        """Gets the href_items of this V2Property.  # noqa: E501


        :return: The href_items of this V2Property.  # noqa: E501
        :rtype: str
        """
        return self._href_items

    @href_items.setter
    def href_items(self, href_items):
        """Sets the href_items of this V2Property.


        :param href_items: The href_items of this V2Property.  # noqa: E501
        :type: str
        """

        self._href_items = href_items

    @property
    def items_displayed_count(self):
        """Gets the items_displayed_count of this V2Property.  # noqa: E501


        :return: The items_displayed_count of this V2Property.  # noqa: E501
        :rtype: int
        """
        return self._items_displayed_count

    @items_displayed_count.setter
    def items_displayed_count(self, items_displayed_count):
        """Sets the items_displayed_count of this V2Property.


        :param items_displayed_count: The items_displayed_count of this V2Property.  # noqa: E501
        :type: int
        """

        self._items_displayed_count = items_displayed_count

    @property
    def items_total_count(self):
        """Gets the items_total_count of this V2Property.  # noqa: E501


        :return: The items_total_count of this V2Property.  # noqa: E501
        :rtype: int
        """
        return self._items_total_count

    @items_total_count.setter
    def items_total_count(self, items_total_count):
        """Sets the items_total_count of this V2Property.


        :param items_total_count: The items_total_count of this V2Property.  # noqa: E501
        :type: int
        """

        self._items_total_count = items_total_count

    @property
    def allow_duplicates(self):
        """Gets the allow_duplicates of this V2Property.  # noqa: E501


        :return: The allow_duplicates of this V2Property.  # noqa: E501
        :rtype: bool
        """
        return self._allow_duplicates

    @allow_duplicates.setter
    def allow_duplicates(self, allow_duplicates):
        """Sets the allow_duplicates of this V2Property.


        :param allow_duplicates: The allow_duplicates of this V2Property.  # noqa: E501
        :type: bool
        """

        self._allow_duplicates = allow_duplicates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2Property, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2Property):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
