# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2RunAccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'experiment_name': 'str',
        'href': 'str',
        'has_access': 'bool'
    }

    attribute_map = {
        'id': 'Id',
        'experiment_name': 'ExperimentName',
        'href': 'Href',
        'has_access': 'HasAccess'
    }

    def __init__(self, id=None, experiment_name=None, href=None, has_access=None):  # noqa: E501
        """V2RunAccess - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._experiment_name = None
        self._href = None
        self._has_access = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if experiment_name is not None:
            self.experiment_name = experiment_name
        if href is not None:
            self.href = href
        if has_access is not None:
            self.has_access = has_access

    @property
    def id(self):
        """Gets the id of this V2RunAccess.  # noqa: E501


        :return: The id of this V2RunAccess.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2RunAccess.


        :param id: The id of this V2RunAccess.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def experiment_name(self):
        """Gets the experiment_name of this V2RunAccess.  # noqa: E501


        :return: The experiment_name of this V2RunAccess.  # noqa: E501
        :rtype: str
        """
        return self._experiment_name

    @experiment_name.setter
    def experiment_name(self, experiment_name):
        """Sets the experiment_name of this V2RunAccess.


        :param experiment_name: The experiment_name of this V2RunAccess.  # noqa: E501
        :type: str
        """

        self._experiment_name = experiment_name

    @property
    def href(self):
        """Gets the href of this V2RunAccess.  # noqa: E501


        :return: The href of this V2RunAccess.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2RunAccess.


        :param href: The href of this V2RunAccess.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def has_access(self):
        """Gets the has_access of this V2RunAccess.  # noqa: E501


        :return: The has_access of this V2RunAccess.  # noqa: E501
        :rtype: bool
        """
        return self._has_access

    @has_access.setter
    def has_access(self, has_access):
        """Sets the has_access of this V2RunAccess.


        :param has_access: The has_access of this V2RunAccess.  # noqa: E501
        :type: bool
        """

        self._has_access = has_access

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2RunAccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2RunAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
