# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2RunCompactSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'date_created': 'datetime',
        'date_modified': 'datetime',
        'user_owned_by': 'IUserCompact',
        'href': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'date_created': 'DateCreated',
        'date_modified': 'DateModified',
        'user_owned_by': 'UserOwnedBy',
        'href': 'Href'
    }

    def __init__(self, id=None, name=None, date_created=None, date_modified=None, user_owned_by=None, href=None):  # noqa: E501
        """V2RunCompactSummary - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._date_created = None
        self._date_modified = None
        self._user_owned_by = None
        self._href = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if date_created is not None:
            self.date_created = date_created
        if date_modified is not None:
            self.date_modified = date_modified
        if user_owned_by is not None:
            self.user_owned_by = user_owned_by
        self.href = href

    @property
    def id(self):
        """Gets the id of this V2RunCompactSummary.  # noqa: E501


        :return: The id of this V2RunCompactSummary.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2RunCompactSummary.


        :param id: The id of this V2RunCompactSummary.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this V2RunCompactSummary.  # noqa: E501


        :return: The name of this V2RunCompactSummary.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2RunCompactSummary.


        :param name: The name of this V2RunCompactSummary.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def date_created(self):
        """Gets the date_created of this V2RunCompactSummary.  # noqa: E501


        :return: The date_created of this V2RunCompactSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this V2RunCompactSummary.


        :param date_created: The date_created of this V2RunCompactSummary.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_modified(self):
        """Gets the date_modified of this V2RunCompactSummary.  # noqa: E501


        :return: The date_modified of this V2RunCompactSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this V2RunCompactSummary.


        :param date_modified: The date_modified of this V2RunCompactSummary.  # noqa: E501
        :type: datetime
        """

        self._date_modified = date_modified

    @property
    def user_owned_by(self):
        """Gets the user_owned_by of this V2RunCompactSummary.  # noqa: E501


        :return: The user_owned_by of this V2RunCompactSummary.  # noqa: E501
        :rtype: IUserCompact
        """
        return self._user_owned_by

    @user_owned_by.setter
    def user_owned_by(self, user_owned_by):
        """Sets the user_owned_by of this V2RunCompactSummary.


        :param user_owned_by: The user_owned_by of this V2RunCompactSummary.  # noqa: E501
        :type: IUserCompact
        """

        self._user_owned_by = user_owned_by

    @property
    def href(self):
        """Gets the href of this V2RunCompactSummary.  # noqa: E501


        :return: The href of this V2RunCompactSummary.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this V2RunCompactSummary.


        :param href: The href of this V2RunCompactSummary.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2RunCompactSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2RunCompactSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
