# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2RunSampleSheetApplication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'settings': 'list[StringStringKeyValuePair]',
        'data': 'list[object]'
    }

    attribute_map = {
        'name': 'Name',
        'settings': 'Settings',
        'data': 'Data'
    }

    def __init__(self, name=None, settings=None, data=None):  # noqa: E501
        """V2RunSampleSheetApplication - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._settings = None
        self._data = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if settings is not None:
            self.settings = settings
        if data is not None:
            self.data = data

    @property
    def name(self):
        """Gets the name of this V2RunSampleSheetApplication.  # noqa: E501


        :return: The name of this V2RunSampleSheetApplication.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V2RunSampleSheetApplication.


        :param name: The name of this V2RunSampleSheetApplication.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def settings(self):
        """Gets the settings of this V2RunSampleSheetApplication.  # noqa: E501


        :return: The settings of this V2RunSampleSheetApplication.  # noqa: E501
        :rtype: list[StringStringKeyValuePair]
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this V2RunSampleSheetApplication.


        :param settings: The settings of this V2RunSampleSheetApplication.  # noqa: E501
        :type: list[StringStringKeyValuePair]
        """

        self._settings = settings

    @property
    def data(self):
        """Gets the data of this V2RunSampleSheetApplication.  # noqa: E501


        :return: The data of this V2RunSampleSheetApplication.  # noqa: E501
        :rtype: list[object]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this V2RunSampleSheetApplication.


        :param data: The data of this V2RunSampleSheetApplication.  # noqa: E501
        :type: list[object]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2RunSampleSheetApplication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2RunSampleSheetApplication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
