# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppSessionCompact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'href': 'str',
        'application': 'V1pre3ApplicationCompact',
        'user_created_by': 'V1pre3UserCompact',
        'status': 'str',
        'qc_status': 'str',
        'status_summary': 'str',
        'purpose': 'str',
        'date_created': 'datetime',
        'modified_on': 'datetime',
        'date_completed': 'datetime',
        'total_size': 'int',
        'properties': 'V2PropertyContainer',
        'is_deleted': 'bool'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'href': 'Href',
        'application': 'Application',
        'user_created_by': 'UserCreatedBy',
        'status': 'Status',
        'qc_status': 'QcStatus',
        'status_summary': 'StatusSummary',
        'purpose': 'Purpose',
        'date_created': 'DateCreated',
        'modified_on': 'ModifiedOn',
        'date_completed': 'DateCompleted',
        'total_size': 'TotalSize',
        'properties': 'Properties',
        'is_deleted': 'IsDeleted'
    }

    def __init__(self, id=None, name=None, href=None, application=None, user_created_by=None, status=None, qc_status=None, status_summary=None, purpose=None, date_created=None, modified_on=None, date_completed=None, total_size=None, properties=None, is_deleted=None):  # noqa: E501
        """AppSessionCompact - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._href = None
        self._application = None
        self._user_created_by = None
        self._status = None
        self._qc_status = None
        self._status_summary = None
        self._purpose = None
        self._date_created = None
        self._modified_on = None
        self._date_completed = None
        self._total_size = None
        self._properties = None
        self._is_deleted = None
        self.discriminator = None
        self.id = id
        if name is not None:
            self.name = name
        self.href = href
        if application is not None:
            self.application = application
        if user_created_by is not None:
            self.user_created_by = user_created_by
        if status is not None:
            self.status = status
        if qc_status is not None:
            self.qc_status = qc_status
        if status_summary is not None:
            self.status_summary = status_summary
        if purpose is not None:
            self.purpose = purpose
        if date_created is not None:
            self.date_created = date_created
        if modified_on is not None:
            self.modified_on = modified_on
        if date_completed is not None:
            self.date_completed = date_completed
        if total_size is not None:
            self.total_size = total_size
        if properties is not None:
            self.properties = properties
        if is_deleted is not None:
            self.is_deleted = is_deleted

    @property
    def id(self):
        """Gets the id of this AppSessionCompact.  # noqa: E501


        :return: The id of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AppSessionCompact.


        :param id: The id of this AppSessionCompact.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this AppSessionCompact.  # noqa: E501


        :return: The name of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AppSessionCompact.


        :param name: The name of this AppSessionCompact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def href(self):
        """Gets the href of this AppSessionCompact.  # noqa: E501


        :return: The href of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this AppSessionCompact.


        :param href: The href of this AppSessionCompact.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def application(self):
        """Gets the application of this AppSessionCompact.  # noqa: E501


        :return: The application of this AppSessionCompact.  # noqa: E501
        :rtype: V1pre3ApplicationCompact
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this AppSessionCompact.


        :param application: The application of this AppSessionCompact.  # noqa: E501
        :type: V1pre3ApplicationCompact
        """

        self._application = application

    @property
    def user_created_by(self):
        """Gets the user_created_by of this AppSessionCompact.  # noqa: E501


        :return: The user_created_by of this AppSessionCompact.  # noqa: E501
        :rtype: V1pre3UserCompact
        """
        return self._user_created_by

    @user_created_by.setter
    def user_created_by(self, user_created_by):
        """Sets the user_created_by of this AppSessionCompact.


        :param user_created_by: The user_created_by of this AppSessionCompact.  # noqa: E501
        :type: V1pre3UserCompact
        """

        self._user_created_by = user_created_by

    @property
    def status(self):
        """Gets the status of this AppSessionCompact.  # noqa: E501


        :return: The status of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AppSessionCompact.


        :param status: The status of this AppSessionCompact.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def qc_status(self):
        """Gets the qc_status of this AppSessionCompact.  # noqa: E501


        :return: The qc_status of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._qc_status

    @qc_status.setter
    def qc_status(self, qc_status):
        """Sets the qc_status of this AppSessionCompact.


        :param qc_status: The qc_status of this AppSessionCompact.  # noqa: E501
        :type: str
        """

        self._qc_status = qc_status

    @property
    def status_summary(self):
        """Gets the status_summary of this AppSessionCompact.  # noqa: E501


        :return: The status_summary of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._status_summary

    @status_summary.setter
    def status_summary(self, status_summary):
        """Sets the status_summary of this AppSessionCompact.


        :param status_summary: The status_summary of this AppSessionCompact.  # noqa: E501
        :type: str
        """

        self._status_summary = status_summary

    @property
    def purpose(self):
        """Gets the purpose of this AppSessionCompact.  # noqa: E501


        :return: The purpose of this AppSessionCompact.  # noqa: E501
        :rtype: str
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose):
        """Sets the purpose of this AppSessionCompact.


        :param purpose: The purpose of this AppSessionCompact.  # noqa: E501
        :type: str
        """

        self._purpose = purpose

    @property
    def date_created(self):
        """Gets the date_created of this AppSessionCompact.  # noqa: E501


        :return: The date_created of this AppSessionCompact.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this AppSessionCompact.


        :param date_created: The date_created of this AppSessionCompact.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def modified_on(self):
        """Gets the modified_on of this AppSessionCompact.  # noqa: E501


        :return: The modified_on of this AppSessionCompact.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_on

    @modified_on.setter
    def modified_on(self, modified_on):
        """Sets the modified_on of this AppSessionCompact.


        :param modified_on: The modified_on of this AppSessionCompact.  # noqa: E501
        :type: datetime
        """

        self._modified_on = modified_on

    @property
    def date_completed(self):
        """Gets the date_completed of this AppSessionCompact.  # noqa: E501


        :return: The date_completed of this AppSessionCompact.  # noqa: E501
        :rtype: datetime
        """
        return self._date_completed

    @date_completed.setter
    def date_completed(self, date_completed):
        """Sets the date_completed of this AppSessionCompact.


        :param date_completed: The date_completed of this AppSessionCompact.  # noqa: E501
        :type: datetime
        """

        self._date_completed = date_completed

    @property
    def total_size(self):
        """Gets the total_size of this AppSessionCompact.  # noqa: E501


        :return: The total_size of this AppSessionCompact.  # noqa: E501
        :rtype: int
        """
        return self._total_size

    @total_size.setter
    def total_size(self, total_size):
        """Sets the total_size of this AppSessionCompact.


        :param total_size: The total_size of this AppSessionCompact.  # noqa: E501
        :type: int
        """

        self._total_size = total_size

    @property
    def properties(self):
        """Gets the properties of this AppSessionCompact.  # noqa: E501


        :return: The properties of this AppSessionCompact.  # noqa: E501
        :rtype: V2PropertyContainer
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this AppSessionCompact.


        :param properties: The properties of this AppSessionCompact.  # noqa: E501
        :type: V2PropertyContainer
        """

        self._properties = properties

    @property
    def is_deleted(self):
        """Gets the is_deleted of this AppSessionCompact.  # noqa: E501


        :return: The is_deleted of this AppSessionCompact.  # noqa: E501
        :rtype: bool
        """
        return self._is_deleted

    @is_deleted.setter
    def is_deleted(self, is_deleted):
        """Sets the is_deleted of this AppSessionCompact.


        :param is_deleted: The is_deleted of this AppSessionCompact.  # noqa: E501
        :type: bool
        """

        self._is_deleted = is_deleted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppSessionCompact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppSessionCompact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
