# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Reference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rel': 'str',
        'type': 'str',
        'href': 'str',
        'href_content': 'str',
        'name': 'str',
        'content': 'V1pre3ProjectCompact'
    }

    attribute_map = {
        'rel': 'Rel',
        'type': 'Type',
        'href': 'Href',
        'href_content': 'HrefContent',
        'name': 'Name',
        'content': 'Content'
    }

    def __init__(self, rel=None, type=None, href=None, href_content=None, name=None, content=None):  # noqa: E501
        """Reference - a model defined in Swagger"""  # noqa: E501
        self._rel = None
        self._type = None
        self._href = None
        self._href_content = None
        self._name = None
        self._content = None
        self.discriminator = None
        if rel is not None:
            self.rel = rel
        if type is not None:
            self.type = type
        if href is not None:
            self.href = href
        if href_content is not None:
            self.href_content = href_content
        if name is not None:
            self.name = name
        if content is not None:
            self.content = content

    @property
    def rel(self):
        """Gets the rel of this Reference.  # noqa: E501


        :return: The rel of this Reference.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this Reference.


        :param rel: The rel of this Reference.  # noqa: E501
        :type: str
        """

        self._rel = rel

    @property
    def type(self):
        """Gets the type of this Reference.  # noqa: E501


        :return: The type of this Reference.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Reference.


        :param type: The type of this Reference.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def href(self):
        """Gets the href of this Reference.  # noqa: E501


        :return: The href of this Reference.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Reference.


        :param href: The href of this Reference.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def href_content(self):
        """Gets the href_content of this Reference.  # noqa: E501


        :return: The href_content of this Reference.  # noqa: E501
        :rtype: str
        """
        return self._href_content

    @href_content.setter
    def href_content(self, href_content):
        """Sets the href_content of this Reference.


        :param href_content: The href_content of this Reference.  # noqa: E501
        :type: str
        """

        self._href_content = href_content

    @property
    def name(self):
        """Gets the name of this Reference.  # noqa: E501


        :return: The name of this Reference.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Reference.


        :param name: The name of this Reference.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def content(self):
        """Gets the content of this Reference.  # noqa: E501


        :return: The content of this Reference.  # noqa: E501
        :rtype: V1pre3ProjectCompact
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Reference.


        :param content: The content of this Reference.  # noqa: E501
        :type: V1pre3ProjectCompact
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Reference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Reference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
