# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubscriptionStorage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unit_of_measure': 'str',
        'quota': 'float'
    }

    attribute_map = {
        'unit_of_measure': 'UnitOfMeasure',
        'quota': 'Quota'
    }

    def __init__(self, unit_of_measure=None, quota=None):  # noqa: E501
        """SubscriptionStorage - a model defined in Swagger"""  # noqa: E501
        self._unit_of_measure = None
        self._quota = None
        self.discriminator = None
        if unit_of_measure is not None:
            self.unit_of_measure = unit_of_measure
        if quota is not None:
            self.quota = quota

    @property
    def unit_of_measure(self):
        """Gets the unit_of_measure of this SubscriptionStorage.  # noqa: E501


        :return: The unit_of_measure of this SubscriptionStorage.  # noqa: E501
        :rtype: str
        """
        return self._unit_of_measure

    @unit_of_measure.setter
    def unit_of_measure(self, unit_of_measure):
        """Sets the unit_of_measure of this SubscriptionStorage.


        :param unit_of_measure: The unit_of_measure of this SubscriptionStorage.  # noqa: E501
        :type: str
        """

        self._unit_of_measure = unit_of_measure

    @property
    def quota(self):
        """Gets the quota of this SubscriptionStorage.  # noqa: E501


        :return: The quota of this SubscriptionStorage.  # noqa: E501
        :rtype: float
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """Sets the quota of this SubscriptionStorage.


        :param quota: The quota of this SubscriptionStorage.  # noqa: E501
        :type: float
        """

        self._quota = quota

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionStorage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionStorage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
