# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2CreateInstrumentDiagnosticRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dataset_type_slug': 'str',
        'id': 'str'
    }

    attribute_map = {
        'dataset_type_slug': 'DatasetTypeSlug',
        'id': 'Id'
    }

    def __init__(self, dataset_type_slug=None, id=None):  # noqa: E501
        """V2CreateInstrumentDiagnosticRequest - a model defined in Swagger"""  # noqa: E501
        self._dataset_type_slug = None
        self._id = None
        self.discriminator = None
        self.dataset_type_slug = dataset_type_slug
        self.id = id

    @property
    def dataset_type_slug(self):
        """Gets the dataset_type_slug of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501


        :return: The dataset_type_slug of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501
        :rtype: str
        """
        return self._dataset_type_slug

    @dataset_type_slug.setter
    def dataset_type_slug(self, dataset_type_slug):
        """Sets the dataset_type_slug of this V2CreateInstrumentDiagnosticRequest.


        :param dataset_type_slug: The dataset_type_slug of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501
        :type: str
        """
        if dataset_type_slug is None:
            raise ValueError("Invalid value for `dataset_type_slug`, must not be `None`")  # noqa: E501

        self._dataset_type_slug = dataset_type_slug

    @property
    def id(self):
        """Gets the id of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501

        The Id of the resource  # noqa: E501

        :return: The id of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2CreateInstrumentDiagnosticRequest.

        The Id of the resource  # noqa: E501

        :param id: The id of this V2CreateInstrumentDiagnosticRequest.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2CreateInstrumentDiagnosticRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2CreateInstrumentDiagnosticRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
