# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2PostUsersIdV2BioSampleRegistryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'v2_bio_sample_registry_enabled': 'bool',
        'override_v1_v2_toggle_switch_code_feature': 'bool'
    }

    attribute_map = {
        'v2_bio_sample_registry_enabled': 'V2BioSampleRegistryEnabled',
        'override_v1_v2_toggle_switch_code_feature': 'OverrideV1V2ToggleSwitchCodeFeature'
    }

    def __init__(self, v2_bio_sample_registry_enabled=None, override_v1_v2_toggle_switch_code_feature=None):  # noqa: E501
        """V2PostUsersIdV2BioSampleRegistryRequest - a model defined in Swagger"""  # noqa: E501
        self._v2_bio_sample_registry_enabled = None
        self._override_v1_v2_toggle_switch_code_feature = None
        self.discriminator = None
        self.v2_bio_sample_registry_enabled = v2_bio_sample_registry_enabled
        self.override_v1_v2_toggle_switch_code_feature = override_v1_v2_toggle_switch_code_feature

    @property
    def v2_bio_sample_registry_enabled(self):
        """Gets the v2_bio_sample_registry_enabled of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501


        :return: The v2_bio_sample_registry_enabled of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._v2_bio_sample_registry_enabled

    @v2_bio_sample_registry_enabled.setter
    def v2_bio_sample_registry_enabled(self, v2_bio_sample_registry_enabled):
        """Sets the v2_bio_sample_registry_enabled of this V2PostUsersIdV2BioSampleRegistryRequest.


        :param v2_bio_sample_registry_enabled: The v2_bio_sample_registry_enabled of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501
        :type: bool
        """
        if v2_bio_sample_registry_enabled is None:
            raise ValueError("Invalid value for `v2_bio_sample_registry_enabled`, must not be `None`")  # noqa: E501

        self._v2_bio_sample_registry_enabled = v2_bio_sample_registry_enabled

    @property
    def override_v1_v2_toggle_switch_code_feature(self):
        """Gets the override_v1_v2_toggle_switch_code_feature of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501


        :return: The override_v1_v2_toggle_switch_code_feature of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501
        :rtype: bool
        """
        return self._override_v1_v2_toggle_switch_code_feature

    @override_v1_v2_toggle_switch_code_feature.setter
    def override_v1_v2_toggle_switch_code_feature(self, override_v1_v2_toggle_switch_code_feature):
        """Sets the override_v1_v2_toggle_switch_code_feature of this V2PostUsersIdV2BioSampleRegistryRequest.


        :param override_v1_v2_toggle_switch_code_feature: The override_v1_v2_toggle_switch_code_feature of this V2PostUsersIdV2BioSampleRegistryRequest.  # noqa: E501
        :type: bool
        """
        if override_v1_v2_toggle_switch_code_feature is None:
            raise ValueError("Invalid value for `override_v1_v2_toggle_switch_code_feature`, must not be `None`")  # noqa: E501

        self._override_v1_v2_toggle_switch_code_feature = override_v1_v2_toggle_switch_code_feature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2PostUsersIdV2BioSampleRegistryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2PostUsersIdV2BioSampleRegistryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
