# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2PartEtag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'part': 'int',
        'etag': 'str'
    }

    attribute_map = {
        'part': 'Part',
        'etag': 'Etag'
    }

    def __init__(self, part=None, etag=None):  # noqa: E501
        """V2PartEtag - a model defined in Swagger"""  # noqa: E501
        self._part = None
        self._etag = None
        self.discriminator = None
        self.part = part
        self.etag = etag

    @property
    def part(self):
        """Gets the part of this V2PartEtag.  # noqa: E501


        :return: The part of this V2PartEtag.  # noqa: E501
        :rtype: int
        """
        return self._part

    @part.setter
    def part(self, part):
        """Sets the part of this V2PartEtag.


        :param part: The part of this V2PartEtag.  # noqa: E501
        :type: int
        """
        if part is None:
            raise ValueError("Invalid value for `part`, must not be `None`")  # noqa: E501

        self._part = part

    @property
    def etag(self):
        """Gets the etag of this V2PartEtag.  # noqa: E501


        :return: The etag of this V2PartEtag.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this V2PartEtag.


        :param etag: The etag of this V2PartEtag.  # noqa: E501
        :type: str
        """
        if etag is None:
            raise ValueError("Invalid value for `etag`, must not be `None`")  # noqa: E501

        self._etag = etag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2PartEtag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2PartEtag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
