# coding: utf-8

"""
    Basespace API

    Basespace REST API  # noqa: E501

    OpenAPI spec version: 5.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V2PostAppSessionsWorkflowSessionsTrackRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meta_workflow_user_reference': 'str',
        'ica_project_id': 'str',
        'id': 'str'
    }

    attribute_map = {
        'meta_workflow_user_reference': 'MetaWorkflowUserReference',
        'ica_project_id': 'IcaProjectId',
        'id': 'Id'
    }

    def __init__(self, meta_workflow_user_reference=None, ica_project_id=None, id=None):  # noqa: E501
        """V2PostAppSessionsWorkflowSessionsTrackRequest - a model defined in Swagger"""  # noqa: E501
        self._meta_workflow_user_reference = None
        self._ica_project_id = None
        self._id = None
        self.discriminator = None
        self.meta_workflow_user_reference = meta_workflow_user_reference
        self.ica_project_id = ica_project_id
        self.id = id

    @property
    def meta_workflow_user_reference(self):
        """Gets the meta_workflow_user_reference of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501


        :return: The meta_workflow_user_reference of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :rtype: str
        """
        return self._meta_workflow_user_reference

    @meta_workflow_user_reference.setter
    def meta_workflow_user_reference(self, meta_workflow_user_reference):
        """Sets the meta_workflow_user_reference of this V2PostAppSessionsWorkflowSessionsTrackRequest.


        :param meta_workflow_user_reference: The meta_workflow_user_reference of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :type: str
        """
        if meta_workflow_user_reference is None:
            raise ValueError("Invalid value for `meta_workflow_user_reference`, must not be `None`")  # noqa: E501

        self._meta_workflow_user_reference = meta_workflow_user_reference

    @property
    def ica_project_id(self):
        """Gets the ica_project_id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501


        :return: The ica_project_id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :rtype: str
        """
        return self._ica_project_id

    @ica_project_id.setter
    def ica_project_id(self, ica_project_id):
        """Sets the ica_project_id of this V2PostAppSessionsWorkflowSessionsTrackRequest.


        :param ica_project_id: The ica_project_id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :type: str
        """
        if ica_project_id is None:
            raise ValueError("Invalid value for `ica_project_id`, must not be `None`")  # noqa: E501

        self._ica_project_id = ica_project_id

    @property
    def id(self):
        """Gets the id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501

        The Id of the resource  # noqa: E501

        :return: The id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V2PostAppSessionsWorkflowSessionsTrackRequest.

        The Id of the resource  # noqa: E501

        :param id: The id of this V2PostAppSessionsWorkflowSessionsTrackRequest.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V2PostAppSessionsWorkflowSessionsTrackRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V2PostAppSessionsWorkflowSessionsTrackRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
